name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@bb45937a053e097f8591208d8e74c90db1873d07 # master
        with:
          toolchain: 1.77.2
          components: rustfmt
      - name: Format check
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@bb45937a053e097f8591208d8e74c90db1873d07 # master
        with:
          toolchain: 1.77.2
          components: clippy
      - name: Clippy
        run: cargo clippy -- --deny warnings

  build:
    name: build (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: aarch64-apple-darwin, os: macos-14 }
          #- { target: aarch64-pc-windows-gnullvm, os: ubuntu-22.04 }
          - { target: aarch64-pc-windows-msvc, os: windows-2022 }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-22.04 }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-22.04 }
          - { target: armv7-unknown-linux-gnueabi, os: ubuntu-22.04 }
          - { target: armv7-unknown-linux-gnueabihf, os: ubuntu-22.04 }
          - { target: armv7-unknown-linux-musleabi, os: ubuntu-22.04 }
          - { target: armv7-unknown-linux-musleabihf, os: ubuntu-22.04 }
          - { target: x86_64-apple-darwin, os: macos-14 }
          - { target: x86_64-pc-windows-gnu, os: ubuntu-22.04 }
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-22.04 }
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.job.target }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@bb45937a053e097f8591208d8e74c90db1873d07 # master
        with:
          toolchain: 1.77.2
          targets: ${{ matrix.job.target }}
      - name: Install cross
        run: cargo install --force cross
        if: runner.os == 'Linux'
      - name: Build
        run: cargo build --locked --target=${{ matrix.job.target }}
        if: runner.os != 'Linux'
      - name: Build (cross)
        run: cross build --locked --target=${{ matrix.job.target }}
        if: runner.os == 'Linux'

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@bb45937a053e097f8591208d8e74c90db1873d07 # master
        with:
          toolchain: 1.77.2
      - name: Test
        run: cargo test --all-targets --all-features

  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@bb45937a053e097f8591208d8e74c90db1873d07 # master
        with:
          toolchain: 1.77.2
      - name: Audit
        run: cargo audit
